# Contiguous 
Array are contiguous because it used same data type and same location

# Homogeneous 
All elements in a collection are of same data type

# Heterogeneous 
Elements on the collection are on different data types

# Difference between Array and List
1) Arrays are homogeneous and **list are heterogeneous**
2) Arrays are Multidimensional and **list are one dimensional**
3) Array stores data in Contiguous memory and **list doesn't store data in contiguous memory**
4) Arrays are faster in comparision to list
5) List is slower as compared to arrays
6) Array follows SIMD- Single instruction multiple data
7) List Doesn't follow SIMD

# Numpy

Numpy popularly known as "Numerical Python" and its a core library for numeric and scientific computing.
It consist of multi-dimensional array
Its Homogeneous in nature
The numpy array contains single data type

# 1-D Array is vector
# 2-D Array is matrix - Consist of rows and column
# 3-D Array is Tensor - Consist of sets, rows, column

!pip install numpy (3rd party package) (if it is not present in the system)

import warnings
warnings.filterwarnings("ignore") # to ignore any warnings from the system to showcase in the output

In [1]:
import numpy

In [3]:
numpy.__version__

'1.24.3'

In [4]:
import numpy as np

In [6]:
?np

In [7]:
l1 = [35,6.28,4]
print(l1)    # heterogenous in nature list
print(type(l1))

[35, 6.28, 4]
<class 'list'>


In [8]:
l1 = [35,6.28,"Abc",4]
print(l1)    # heterogenous in nature list
print(type(l1))     # We have created list here to just compare list and array 

[35, 6.28, 'Abc', 4]
<class 'list'>


In [ ]:
# Incorrect way to create an array
#a1 = array([35,6.28,"Abc",4])
# print(a1)   name 'array' is not defined - error

In [9]:
a1 = np.array([35,6.28,4])  # For creating a Numpy array, use square brackets [] inside the np.array() function
print(a1)
type(a1)

[35.    6.28  4.  ]


numpy.ndarray

In [10]:
a1 = np.array([35,6.28,"Abc",4]) # String are called object
# In numpy, we use [] to define the element of the array, and () to call the array() function.
print(a1)  #homogeneous in nature Means it will not accept mixed data type
print(type(a1))
# As we provided mixed data type it will convert to string

['35' '6.28' 'Abc' '4']
<class 'numpy.ndarray'>


In [11]:
A1 = np.array([35,6.28,"Abc",4])
# Getting the dimensions
print(A1.ndim)
# ndim is used to find the dimension of array

1


In [37]:
arr = np.array([1, 2, 3, 4])

print(arr * 2)  

# Multi-dimensional array
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d * 2)
print(arr2d.ndim)
print(arr2d.shape)

[2 4 6 8]
[[2 4]
 [6 8]]
2
(2, 2)


In [21]:
A2 = np.array([35,6.28,"efg",4])
print(A2)
print(type(A2))
A2.shape  # To check the shape of array with dimension, output showing columns are empty

['35' '6.28' 'efg' '4']
<class 'numpy.ndarray'>


(4,)

# Allocating Size

When we give a size like int32, float64, etc.
We are telling python how much memory to use and how accurate the numbers should be

Why we do it:
Save memory - smaller size - use less space
Faster - smaller data is quicker to process
Better control - we choose how exact we want the numbers
Useful when working with big data or ML models

In [29]:
a3 = np.array([34,45,901,56.78,21.26,-102], dtype ="int64")  # datatype
print(a3)


# **dtype**
# It tells Numpy what type of data to store in the array
# All elements are converted to 64-bit integers
# So decimal parts (.78, .26) will be truncated (not rounded)

[  34   45  901   56   21 -102]


In [33]:
float1 = np.array([22,34,56,78,43,56], dtype="f")
print(float1)    # didn't mentioned size so by default it will take 32-bit float

[22. 34. 56. 78. 43. 56.]


In [34]:
float1 = np.array([22,34,56,78,43,56], dtype="float64")
print(float1)

[22. 34. 56. 78. 43. 56.]


In [ ]:
# 2D Array

In [42]:
s1 = np.array([[12,23,34,45],[56,67,78,89]])
print(s1)
print("Dimension:",s1.ndim)
print("Shape:",s1.shape)

[[12 23 34 45]
 [56 67 78 89]]
Dimension: 2
Shape: (2, 4)


In [45]:
s24 = np.array([[[12,23,34,45],[56,67,78,89,91]]]) # if given more value it will consider 1D list
print(s24)
print("Dimension:",s24.ndim)
print("Shape:",s24.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.

In [48]:
?np.array

In [51]:
s24 = np.array([[12,"P",2.3,34,"i",45],[56,"y",6.7,78,"u",89],[32,"s",4.1,51,"h",81]]) # mixed data type
print(s24)
print("Dimension:",s24.ndim)
print("Shape:",s24.shape)

[['12' 'P' '2.3' '34' 'i' '45']
 ['56' 'y' '6.7' '78' 'u' '89']
 ['32' 's' '4.1' '51' 'h' '81']]
Dimension: 2
Shape: (3, 6)


In [ ]:
# 3D Array - Combination of n number of 2D array

In [53]:
s25 = np.array([
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]]])
print(s25)
print("Dimension:",s25.ndim)
print("Shape:",s25.shape)    # Shape: (2, 2, 3):- 2 -> sets, 2 -> rows, 3 -> number of columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension: 3
Shape: (2, 2, 3)


In [55]:
s25 = np.array([
        [[1, 2,"Piyush", 3], [4, 5,"Mishra", 6]],
        [[7, 8,"Piyush", 9], [10, 11,"Mishra", 12]]])
print(s25)
print("Dimension:",s25.ndim)
print("Shape:",s25.shape)

[[['1' '2' 'Piyush' '3']
  ['4' '5' 'Mishra' '6']]

 [['7' '8' 'Piyush' '9']
  ['10' '11' 'Mishra' '12']]]
Dimension: 3
Shape: (2, 2, 4)


# Indexing with Array

In [57]:
l1 = [3,4,5,7,6,[1,2,8,9]]
print(l1)
type(l1)
l1[-1]

[3, 4, 5, 7, 6, [1, 2, 8, 9]]


[1, 2, 8, 9]

In [60]:
l1 = np.array([3,4,5,7,6,1,2,8,9])
print(l1)
type(l1)
l1[-1]

[3 4 5 7 6 1 2 8 9]


9

In [62]:
# 1D Array indexing

l1 = np.array([3,4,5,7,6,1,2,8.5])
print(l1.ndim)
print(l1.shape)
print(l1)
print(l1[2])
print(l1[4:6])
print(l1[-3:-4])
print(l1[1:-1])


1
(8,)
[3.  4.  5.  7.  6.  1.  2.  8.5]
5.0
[6. 1.]
[]
[4. 5. 7. 6. 1. 2.]


In [63]:
# 2D Array indexing

b = [[3,4,5],[78,9,0],[45,-2,-283]]
print(b)

[[3, 4, 5], [78, 9, 0], [45, -2, -283]]


In [65]:
b1 = np.array([[3,4,5],[78,9,0],[45,-2,-283]])
print(b1)

[[   3    4    5]
 [  78    9    0]
 [  45   -2 -283]]


In [66]:
b[1][0]  # indexing of List

78

In [80]:
print(b1[1,0])  # indexing of Array
print(b1[1,:2])
print(b1[2,2])

78
[78  9]
-283


In [82]:
# Indexing and Slicing of Array
print(b1)
print(b1[1,1])
print(b1[2,-1])
print(b1[:,1])
print(b1[0:2,0:2])
print(b1[:,[0,2]])

[[   3    4    5]
 [  78    9    0]
 [  45   -2 -283]]
9
-283
[ 4  9 -2]
[[ 3  4]
 [78  9]]
[[   3    5]
 [  78    0]
 [  45 -283]]


In [88]:
array_3d = np.array([[[1, 2, 3],[5, 6, 7],[9, 10, 11]],[[13, 14, 15],[17, 18, 19],[21, 22, 23]]])

print(array_3d)


[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[13 14 15]
  [17 18 19]
  [21 22 23]]]


In [98]:
print(array_3d[1][1][2])
print()
print(array_3d[0])
print()
print(array_3d[:, 0, :])
print()
print(array_3d[:, :, 0])
print()
print(array_3d[1][1][:2])

19

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 1  2  3]
 [13 14 15]]

[[ 1  5  9]
 [13 17 21]]

[17 18]


In [118]:
# Q What is the value at row 1, column 2?
# Q Slice a full row 1
# Q Print the third column

a2d = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(a2d)
print()
print(a2d[1,2])
print()
print(a2d[1])
print()
print("Last column",a2d[:,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]

60

[40 50 60]

Last column [30 60 90]


In [121]:
# Q 
# Q Slice a full 2D block from a 3D array
a3d = np.array([[[1,2],[3,4]],
                [[5,6],[7,8]],
               [[9,10],[11,12]]])
print(a3d)
print()
print(a3d[2,1,0])
print()
print("set",a3d[0])

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

11

set [[1 2]
 [3 4]]


# SIMD stands for Single Instruction, Multiple Data.

SIMD One instruction, applied to many data points at once.

Used in NumPy for fast operations.

Helps in faster computation, especially for large arrays

In [123]:
import numpy as np

# without SIMD (regular Python)

data = [1, 2, 3, 4]

result = []

for x in data:
    result.append(x + 5)

print("Without SIMD:", result)

Without SIMD: [6, 7, 8, 9]


In [125]:
# with SIMD (NumPy does it internally)

arr = np.array([1, 2, 3, 4])
result_simd = arr + 5

print("With SIMD:", result_simd)

With SIMD: [6 7 8 9]


In [1]:
import numpy as np

In [ ]:
# Array of 1 - ones

In [2]:
?np.ones

In [3]:
# For 1-D with all ones

np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# For 2-D with all ones

s = (3,4)
np.ones(s)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# For 3-D with all ones

s = (3,4,2)   # 3 blocks, each with 4 rows and 2 columns
np.ones(s)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
np.ones(s, dtype = int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
# For np.zeros

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
s = (2,3)
np.zeros(s)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
s = (2,3,4)
np.zeros(s)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.zeros(s, dtype = int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [25]:
?np.full

In [18]:
np.full((2), np.inf) # For np.full we have to give the value which we want in our output

array([inf, inf])

In [15]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [27]:
np.full((2,3,3), [1,2,3])   # 2 Sets, 3 rows 3 column

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [30]:
np.full(5, "P")    # It will consdier string too

array(['P', 'P', 'P', 'P', 'P'], dtype='<U1')

In [35]:
?np.linspace

# np.linspace (Start, stop, num)

Returns evenly spaced values between start and stop
Useful when you want a specific number of values in a range (e.g, Plotting)

In [38]:
np.linspace(1, 50, 5, dtype = int)

array([ 1, 13, 25, 37, 50])

np.identity()
np.identity(n) creates an n x n square matrix with 1's on the diagonal and 0's elsewhere
Only works for 2D square matrices
You cannot create 1D or 3D identity matrices using np.identity()

In [43]:
# 2D Identity Matrix of size 3x3
# Diagonal elements are 1,rest are 0

np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
?np.arange

# np.arange

Returns values from start to stop (exclusive) with given step
Like python's range(), but returns a Numpy array

In [53]:
np.arange(0, 11, 2)    # start, stop, step

array([ 0,  2,  4,  6,  8, 10])

# np.random.randint (low, high, size)

Generates random integers from low (Inclusive) to high (exclusive)
For generating random numbers in a specific range

In [56]:
arr = np.random.randint(10, 50, size = (2,))
print(arr)

[27 23]


In [58]:
arr = np.random.randint(10, 50, size = (2, 3))
print(arr)

[[38 28 28]
 [46 10 16]]


In [60]:
arr = np.random.randint(10, 50, size = (2, 3, 3))
print(arr)

[[[40 18 16]
  [40 13 14]
  [17 32 36]]

 [[45 13 36]
  [17 23 13]
  [16 20 39]]]


# np.random.random(size)

Returns random floats beteen 0 and 1
To create random decimal values

In [62]:
arr = np.random.random((2,))    # 1-D array
print(arr)

[0.38336019 0.76049046]


In [63]:
arr = np.random.random((2,3))    # 2-D array
print(arr)

[[0.32318086 0.42043327 0.64256842]
 [0.4674263  0.40118999 0.28063743]]


In [64]:
arr = np.random.random((2,3,3))    # 3-D array
print(arr)

[[[0.22096175 0.09919995 0.38624784]
  [0.11554512 0.10312858 0.70589806]
  [0.61382702 0.02288912 0.17776909]]

 [[0.81494224 0.47752787 0.94721274]
  [0.61418382 0.36836024 0.86784456]
  [0.33535087 0.71900496 0.11232069]]]


# np.random.uniform()

Generates random float numbers in a specified range

In [66]:
# 1-D with uniform
arr = np.random.uniform(10, 20, size = 5)
print("Uniform:", arr)

Uniform: [19.14023958 16.95423015 13.34419241 10.76424748 11.47410082]


In [68]:
# 2-D with uniform
arr = np.random.uniform(10, 20, size = (2,3))
print("Uniform:", arr)

Uniform: [[11.02789218 19.8482044  19.1161779 ]
 [10.89611421 19.53680886 18.29996348]]


In [70]:
np.random.seed(42)

arr = np.random.uniform(10, 20, size=(2, 3))
print("Uniform:", arr)

Uniform: [[13.74540119 19.50714306 17.31993942]
 [15.98658484 11.5601864  11.5599452 ]]


# Reshape

It is primarily refers to changing the dimensions of a data structure, without altering its underlying data.

In [2]:
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2x3 matrix
reshaped_arr = arr.reshape((2, 3))
print("Reshaped 2x3 array:")
print(reshaped_arr)

# Reshape the array into a 3x2 matrix using -1 for an unknown dimension
reshaped_arr_auto = arr.reshape((3, -1))
print("\nReshaped 3x2 array (with -1):")
print(reshaped_arr_auto)

Reshaped 2x3 array:
[[1 2 3]
 [4 5 6]]

Reshaped 3x2 array (with -1):
[[1 2]
 [3 4]
 [5 6]]


# Flatten()

Returns a copy of the array collapsed into 1-D (to flatten a numpy array)

In [8]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [9]:
flat = a.flatten()
print(flat)

[1 2 3 4]


In [ ]:
# Mathematical Functions

In [10]:
l1 = [3,4,5,6,7.5]   # list will get replicated
print(l1)
l1*2

[3, 4, 5, 6, 7.5]


[3, 4, 5, 6, 7.5, 3, 4, 5, 6, 7.5]

In [11]:
a1 = np.array([3,4,5,6])   # array will multiply the elements
print(a1)
a1*2

[3 4 5 6]


array([ 6,  8, 10, 12])

In [12]:
x = np.array([[3,5],[2,4]])
print(x)

[[3 5]
 [2 4]]


In [13]:
y = np.array([[2,3],[5,7]])
print(y)

[[2 3]
 [5 7]]


In [14]:
x + y

array([[ 5,  8],
       [ 7, 11]])

In [15]:
x - y

array([[ 1,  2],
       [-3, -3]])

In [16]:
x * y

array([[ 6, 15],
       [10, 28]])

In [17]:
x / y

array([[1.5       , 1.66666667],
       [0.4       , 0.57142857]])

# Aggregate function

np.min(a)

np.max(a)

np.sum(a)

np.mean(a)

np.prod(a)

np.medium(a)

np.std(a)

np.var(a)

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Aggregations over the entire array
print(f"Minimum value: {np.min(arr)}")
print(f"Maximum value: {np.max(arr)}")
print(f"Sum of elements: {np.sum(arr)}")
print(f"Mean of elements: {np.mean(arr)}")
print(f"Product of elements: {np.prod(arr)}")
print(f"Median of elements: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")    # while standard deviation is the square root of the variance
print(f"Variance: {np.var(arr)}")             # variance represents the average of the squared differences from the mean

# Aggregations along a specific axis (e.g., axis=0 for columns)
print(f"Column-wise sum: {np.sum(arr, axis=0)}")

Minimum value: 1
Maximum value: 6
Sum of elements: 21
Mean of elements: 3.5
Product of elements: 720
Median of elements: 3.5
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665
Column-wise sum: [5 7 9]


# Math Functions

np.sqrt(a)

np.exp(a)

np.log(a)

np.log10(a)

np.sin(a)

np.cos(a)

np.round(b,2)

np.floor(b)

np.ceil(b)

In [30]:
a = np.array([1, 4, 9, 16])
b = np.array([3.14159, 2.71828, 5.98765, 1.23456])


print("Square root:", np.sqrt(a))


print("Exponential:", np.exp(a))        


print("Natural Log:", np.log(a))       


print("Log base 10:", np.log10(a))      


print("Sine:", np.sin(a))


print("Cosine:", np.cos(a))


print("Rounded:", np.round(b, 2))       


print("Floor:", np.floor(b))            


print("Ceil:", np.ceil(b))             


Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural Log: [0.         1.38629436 2.19722458 2.77258872]
Log base 10: [0.         0.60205999 0.95424251 1.20411998]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Cosine: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
Rounded: [3.14 2.72 5.99 1.23]
Floor: [3. 2. 5. 1.]
Ceil: [4. 3. 6. 2.]


# List Comprehension

List comprehension is a shorter way to create a new list by applying an operation or filter on an existing iterable(like a list or range)

In [31]:
flowers = ["rose", "lily", "tulip", "marigold", "sunflower"]
# we have a list of flower names and we want to convert them to uppercase

In [33]:
# We have a list of flower names we want to convert them to uppercase
# Traditional way of creating a list

flowersList = []
for i in flowers:
    flowersList.append(i.upper())
    print(flowersList)


['ROSE']
['ROSE', 'LILY']
['ROSE', 'LILY', 'TULIP']
['ROSE', 'LILY', 'TULIP', 'MARIGOLD']
['ROSE', 'LILY', 'TULIP', 'MARIGOLD', 'SUNFLOWER']


In [34]:
# Using LC
FlowersList = [i.upper() for i in flowers]
print(FlowersList)

['ROSE', 'LILY', 'TULIP', 'MARIGOLD', 'SUNFLOWER']


In [ ]:
# Create a list of square of numbers from 1 to 5

In [35]:
squares = []
for x in range(1, 6):
    squares.append(x**2)

print(squares)
    

[1, 4, 9, 16, 25]


In [36]:
squares = [x**2 for x in range(1, 6)]
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
# Add 10 to each number in nums = [1,2,3,4] solve using with or without List comprehension

In [37]:
# Without LC
nums = [1, 2, 3, 4]
result = []
for x in nums:
    result.append(x + 10)

print(result)


[11, 12, 13, 14]


In [38]:
# With LC
nums = [1, 2, 3, 4]
result = [x + 10 for x in nums]
print(result)


[11, 12, 13, 14]


In [ ]:
# Get only even numbers in list: [1, 2, 3, 4, 5, 6] solve using with or without List comprehension

In [39]:
# With LC
nums = [1, 2, 3, 4, 5, 6]
evens = [x for x in nums if x % 2 == 0]
print(evens)

[2, 4, 6]


In [40]:
# Without LC
nums = [1, 2, 3, 4, 5, 6]
evens = []

for x in nums:
    if x % 2 == 0:
        evens.append(x)

print(evens)

[2, 4, 6]


In [ ]:
# LC with if-else
# Syntax

# [expression_if_true if condition else expression_if_false for item in iterable]

In [49]:
nums = [1, 2, 3, 4, 5]
result = []

for x in nums:
    if x % 2 == 0:
        result.append(f"{x}: Even")
    else:
        result.append(f"{x}: Odd")

print(result)

['1: Odd', '2: Even', '3: Odd', '4: Even', '5: Odd']


In [50]:
nums = [1, 2, 3, 4, 5]
result = [f"{x}: Even" if x % 2 == 0 else f"{x}: Odd" for x in nums]
print(result)

['1: Odd', '2: Even', '3: Odd', '4: Even', '5: Odd']


In [ ]:
# if score >= 40 then pass, else fail solve using with or without list comprehension

In [52]:
scores = [25, 67, 40, 90, 39]
results = [f"{score}: Pass" if score >= 40 else f"{score}: Fail" for score in scores]
print(results)

['25: Fail', '67: Pass', '40: Pass', '90: Pass', '39: Fail']


In [53]:
scores = [25, 67, 40, 90, 39]
results = []

for score in scores:
    if score >= 40:
        results.append(f"{score}: Pass")
    else:
        results.append(f"{score}: Fail")

print(results)


['25: Fail', '67: Pass', '40: Pass', '90: Pass', '39: Fail']
